//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fahrradladen_18._02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikelliste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikelliste()
        {
            this.Rechnungen = new HashSet<Rechnungen>();
        }
    
        public int Artikelliste_ID { get; set; }
        public Nullable<decimal> Gesamtpreis { get; set; }
        public Nullable<int> Artikel_ID { get; set; }
    
        public virtual Artikel Artikel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rechnungen> Rechnungen { get; set; }
    }
}
