//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fahrradladen_18._02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rechnungen
    {
        public int Rechnungs_ID { get; set; }
        public Nullable<int> Artikelliste_ID { get; set; }
        public Nullable<int> Arbeitszeit { get; set; }
    
        public virtual Artikelliste Artikelliste { get; set; }
    }
}
