//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fahrradladen_Abrechnung_Verkauf_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rechnungen
    {
        public int Rechnungs_ID { get; set; }
        public Nullable<int> Artikel_ID { get; set; }
        public Nullable<int> Arbeitszeit { get; set; }
        public Nullable<System.DateTime> Rechnungs_Datum { get; set; }
        public Nullable<decimal> Gesamtpreis { get; set; }
    
        public virtual Artikel Artikel { get; set; }
    }
}
